trigger:
- master

variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  vmImageName: 'windows-2019'

stages:
  - stage: Build

    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
        - script: build.cmd html 
        - script: git clone https://github.com/xqguo/xqguo.github.io
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.SourceFolder)/output'
            Contents: '**'
            TargetFolder: '$(Build.SourceFolder)/xqguo.github.io'
            OverWrite: true
        - task: CmdLine@2
          inputs:
            script: 'publish.bat'
            workingDirectory: '$(Build.SourceFolder)/xqguo.github.io'

