trigger:
- master

variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  vmImageName: 'windows-2019'

stages:
  - stage: Build

    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
        - script: build.cmd html 
        - publish:  $(Agent.BuildDirectory)/output/publish        
  - stage: Deploy
    displayName: Deployment stage
    dependsOn: Build
    condition: succeeded('Build')
    jobs:
    - deployment: Dev
      displayName: Dev
      environment: 'development'
      pool: 
        vmImage: $(vmImageName)
      strategy:
        runOnce:
          deploy:
            steps:
            - script: git clone https://github.com/xqguo/xqguo.github.io
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: 'drop'
                path: $(Build.SourcesDirectory)/xqguo.github.io                     
            - task: CmdLine@2
              inputs:
                script: 'publish.bat'
                workingDirectory: '$(Build.SourcesDirectory)/xqguo.github.io'
