trigger:
- master

variables:
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  vmImageName: 'windows-2019'

stages:
  - stage: Build

    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
        - script: build.cmd html 
        - script: git clone https://github.com/xqguo/xqguo.github.io
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)/output'
            Contents: '**'
            TargetFolder: '$(Build.SourcesDirectory)/xqguo.github.io'
            OverWrite: true
        - task: CmdLine@2
          inputs:
            script: |
              git config --global user.email "guoxiaoq@gmail.com"
              git config --global user.name "Xiaoqiang Guo"
              git status
              git add -A
              git commit -m "update"
              git push git@github.com:xqguo/xqguo.github.io.git
            workingDirectory: '$(Build.SourcesDirectory)/xqguo.github.io'


